dist: trusty
language: php

php:
    - 7.2
    - 7.4
    - 8.0
    - 8.1
    - 8.2

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer self-update || true
    - composer install --dev --prefer-dist

script:
    - vendor/bin/atoum
