name: Application CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: PHP CI ${{ matrix.php-versions }}
    strategy:
      matrix:
        php-versions:
          - 8.0
          - 8.1
          - 8.2
          - 8.3

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run unit tests
        run: vendor/bin/atoum
